name: Env_ExpressivE
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.9
  - pytorch=2.1.1
  - pip
  - pip:
      - pykeen==1.10.1
      - class_resolver==0.3.3
      - setuptools==59.5.0
      - protobuf==3.20.*
      - tensorboard==2.15.1
      - pandas==2.1.4